default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: development_db
  pool: 5
  username: igor
  password: '123456'

test:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: test_db
  pool: 5
  username: igor
  password: '123456'


production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: production_db
  pool: 5
  username: igor
  password: '123456'
